version: "3"

services:
  db:
    image: mariadb:10.3
    restart: always
    ports:
      - "33060:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
  
  wordpress:
    depends_on:
      - db
    image: wordpress:5.1-php7.3-apache
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
    working_dir: /var/www/html
    volumes:
      - wordpress-root:/var/www/html
      - ./themes:/var/www/html/wp-content/themes
      - ./plugins:/var/www/html/wp-content/plugins
  
  wpcli:
    image: wordpress:cli-php7.3
    working_dir: /var/www/html
    volumes:
      - wordpress-root:/var/www/html

volumes:
  wordpress-root: